services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - ticker-network
      
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tickerstream-backend
    expose:
      - "8000"
    volumes:
      - bot_data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/stockBot.db
      - PYTHONPATH=/app/backend
      - SECRET_KEY=your_secure_production_secret_key_here
      - ALLOWED_ORIGINS=["http://localhost","https://ticker-stream.com","https://auth.ticker-stream.com","http://100.85.77.37"]
    networks:
      - ticker-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tickerstream-frontend
    expose:
      - "4000"
    depends_on:
      - backend
    networks:
      - ticker-network
    restart: always

volumes:
  bot_data:

networks:
  ticker-network:
    driver: bridge
    